name: Demande de fonctionnalité
description: Proposer une nouvelle fonctionnalité ou amélioration
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème à résoudre
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution envisagée
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
